/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
// const ninjaone = require('./docs/ninjaone/commandlets/docusaurus.sidebar.js');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "NinjaOne": [
    {
      type: 'doc',
      id: 'index',
    },    
    {
      type: 'autogenerated',
      className: 'commandlet-docs',
      dirName: 'commandlets'
    },
    {
      type: 'category',
      label: 'Filters',
      link: {
        type: 'generated-index',
        title: 'Filters'
      },
      items: [
        {
          type: 'autogenerated',
          className: 'filter-docs',
          dirName: 'filters'
        },
      ]
    },
    {
      type: 'category',
      label: 'Development',
      link: {
        type: 'generated-index',
        title: 'Development'
      },
      items: [
        {
          type: 'autogenerated',
          className: 'dev-docs',
          dirName: 'development'
        },
      ]
    },
    /*{
      type: 'html',
      value: 'Examples',
      className: 'sidebar-title',
    },
    {
      type: 'html',
      value: '&nbsp;',
      className: 'sidebar-spacer',
    },
    {
      type: 'autogenerated',
      dirName: 'examples'
    }*/
  ],
};

module.exports = sidebars;
