/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

//const ninjaget = require('./docs/ninjaget/commandlets/docusaurus.sidebar.js');

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "NinjaGet": [
    {
      type: 'doc',
      id: 'index',
    },
    {
      type: 'autogenerated',
      className: 'commandlet-docs',
      dirName: 'commandlets'
    },
    /*{
      type: 'html',
      value: 'Examples',
      className: 'sidebar-title',
    },
    {
      type: 'html',
      value: '&nbsp;',
      className: 'sidebar-spacer',
    },
    {
      type: 'autogenerated',
      dirName: 'examples'
    }*/
  ],
};

module.exports = sidebars;
