/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
const ninjaone = require('./docs/ninjaone/docusaurus.sidebar.js');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "HaloAPI": [
    {
      type: 'html',
      value: 'DOCUMENTATION!',
      className: 'sidebar-title',
    },
    {
      type: 'html',
      value: '&nbsp;',
      className: 'sidebar-spacer',
    },
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],
};

module.exports = sidebars;
